name: Deploy on master merge

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_SERVER: $${ secrets.NOTES_DEPLOY_IP }}
      DEPLOY_USER: ${{ secrets.NOTES_DEPLOY_USER }}

    steps:
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_NOTES_DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

    - name: Trigger deploy script over SSH
      run: |
        ARGS=""
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          ARGS="${{ github.head_ref }}"
        fi
        ssh -o StrictHostKeyChecking=yes $DEPLOY_USER@$DEPLOY_SERVER "${{ github.repository }}" $ARGS
